title: "LaLaLoc: Latent Layout Localisation in Dynamic, Unvisited Environments"
description: A method to localise in dynamic and unvisited environments through latent representations of room layout.
url: lalaloc.active.vision
signoff: Henry Howard-Jenkins

links:
  - name: <strong>AVLCode</strong>
    url: https://code.active.vision
    external: true
  - name: <strong>GitHub</strong>
    url: https://github.com/ActiveVisionLab/LaLaLoc
    external: true

permalink: pretty
