OUT_DIR: "./runs/lalaloc_pp/plan_branch"
SYSTEM:
  NUM_GPUS: 1
  DISTRIBUTED_BACKEND: "ddp"
  NUM_WORKERS: 16
MODEL:
  TYPE: "lalaloc++"
  QUERY_TYPE: "layout"
  NORMALISE_EMBEDDING: True
  NORMALISE_SAMPLE: True
TRAIN:
  LR_MILESTONES: [50, 75]
  NUM_EPOCHS: 100
  INITIAL_LR: 0.05
  BATCH_SIZE: 16
  TEST_EVERY: 10
  NUM_FAR_SAMPLES: 20
  COMPUTE_GT_DIST: False
TEST:
  POSE_SAMPLE_STEP: 1000
RENDER:
  BATCH_SIZE: 1024
  IMG_SIZE: (128, 256)