OUT_DIR: "./runs/lalaloc_pp/image_branch"
SYSTEM:
  NUM_GPUS: 1
  DISTRIBUTED_BACKEND: "ddp"
  NUM_WORKERS: 16
MODEL:
  TYPE: "lalaloc++"
  QUERY_TYPE: "image"
  PANORAMA_BACKBONE: "resnet50"
  LAYOUT_BACKBONE: "resnet18"
  NORMALISE_EMBEDDING: True
  NORMALISE_SAMPLE: True
  PANO_EMBEDDER_TYPE: "transformer-fc"
  PANORAMA_MODULE:
    POS_AT_INPUT: False
    HIDDEN_DIM: 256
TRAIN:
  SOURCE_WEIGHTS: "trained_models/lalaloc_pp_planbranch.ckpt"
  LR_MILESTONES: [100, 150]
  NUM_EPOCHS: 200
  NEAR_MAX_DIST: 0.5
  INITIAL_LR: 0.1
  BATCH_SIZE: 64
  TEST_EVERY: 50
  NUM_NEAR_SAMPLES: 1
  NUM_FAR_SAMPLES: 0
  COMPUTE_GT_DIST: False
TEST:
  POSE_SAMPLE_STEP: 1000
  LAYOUTS_MAX_BATCH: 256
RENDER:
  BATCH_SIZE: 1024
  IMG_SIZE: (128, 256)
POSE_REFINE:
  RENDER_SIZE: (128, 256)
INPUT:
  NORMALISE_STD: [0.229, 0.224, 0.225]