OUT_DIR: "./runs/ifl/image_branch"
SYSTEM:
  NUM_GPUS: 2
  DISTRIBUTED_BACKEND: "ddp"
  NUM_WORKERS: 0
MODEL:
  QUERY_TYPE: "image"
  PANORAMA_BACKBONE: "resnet50"
  LAYOUT_BACKBONE: "resnet18"
  NORMALISE_EMBEDDING: True
TRAIN:
  SOURCE_WEIGHTS: ""
  LR_MILESTONES: [100, 150]
  NUM_EPOCHS: 200
  NEAR_MAX_DIST: 0.5
  LOSS: "cos"
  INITIAL_LR: 0.1
  BATCH_SIZE: 32
  TEST_EVERY: 20
  NUM_NEAR_SAMPLES: 1
  NUM_FAR_SAMPLES: 0
TEST:
  POSE_SAMPLE_STEP: 1000
  LAYOUTS_MAX_BATCH: 256
RENDER:
  BATCH_SIZE: 1024
  IMG_SIZE: (128, 256)
POSE_REFINE:
  RENDER_SIZE: (128, 256)
