OUT_DIR: "./runs/l2l/layout_branch"
SYSTEM:
  NUM_GPUS: 2
  DISTRIBUTED_BACKEND: "ddp"
  NUM_WORKERS: 0
MODEL:
  QUERY_TYPE: "layout"
  LAYOUT_BACKBONE: "resnet18"
  NORMALISE_EMBEDDING: True
TRAIN:
  LR_MILESTONES: [10, 15]
  NUM_EPOCHS: 20
  NEAR_MAX_DIST: 0.5
  LOSS: "bbs"
  INITIAL_LR: 0.01
  BATCH_SIZE: 4
  TEST_EVERY: 4
  NUM_FAR_SAMPLES: 20
  LAYOUT_LOSS_SCALE: 100.0
  DECODER_LOSS_SCALE: 1.0
TEST:
  POSE_SAMPLE_STEP: 1000
  LAYOUTS_MAX_BATCH: 256
RENDER:
  BATCH_SIZE: 1024
  IMG_SIZE: (128, 256)
POSE_REFINE:
  RENDER_SIZE: (128, 256)